# CloudWatch Configuration
logging.level.root=INFO
logging.level.com.chwimong.project.employment=DEBUG
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}
cloud.aws.region.static=${AWS_REGION}
cloud.aws.stack.auto=false

# Logback configuration
logging.config=classpath:logback-spring.xml